advanced:
  availability_blocklist: []
  availability_passlist: []
  channel: 11
  log_level: warn
  network_key:
  - 1
  - 3
  - 5
  - 7
  - 9
  - 11
  - 13
  - 15
  - 0
  - 2
  - 4
  - 6
  - 8
  - 10
  - 12
  - 13
  pan_id: 6754
blocklist: []
data_path: /config/zigbee2mqtt
device_options: {}
devices: devices.yaml
experimental: {}
external_converters: []
frontend:
  port: 8099
groups: groups.yaml
homeassistant: true
mqtt:
  base_topic: zigbee2mqtt
  login: eratnik
  password: c2h5oh
passlist: []
permit_join: false
queue: {}
serial:
  port: /dev/ttyACM0
socat:
  enabled: false
  log: false
  master: pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777
  options: -d -d
  slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
