# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:
wake_on_lan:
python_script:
noolite:
  port: "/dev/ttyUSB2"

utility_meter:
  monthly_energy_children:
    source: sensor.children_s_spotlight_energy
    name: 'Месячный расход точечных светильников детской'
    cycle: monthly
    tariffs: []
  monthly_energy_nightlight:
    source: sensor.portable_switch_energy
    name: 'Месячный расход Дашин ночник'
    cycle: monthly
    tariffs: []
  monthly_energy_conditioner:
    source: sensor.konditsioner_energy
    name: 'Месячный расход кондиционер'
    cycle: monthly
    tariffs: []
  daily_energy_children:
    source: sensor.children_s_spotlight_energy
    name: 'Дневной расход точечных светильников детской'
    cycle: daily
    tariffs: []
  daily_energy_nightlight:
    source: sensor.portable_switch_energy
    name: 'Дневной расход Дашин ночник'
    cycle: daily
    tariffs: []
  daily_energy_conditioner:
    source: sensor.konditsioner_energy
    name: 'Дневной расход кондиционер'
    cycle: daily
    tariffs: []


#Внешний вид
lovelace:
  mode: storage
frontend:
  themes: !include_dir_merge_named themes
# создание боковой панели с иконками Material disign
# panel_iframe:
#   mdi:
#     title: "Material Design Icons"
#     icon: mdi:material-design
#     url: "https://mdi.bessarabov.com"
panel_custom:
  - name: panel-redirect
    url_path: redirect-server-controls
    sidebar_title: Server Controls
    sidebar_icon: mdi:server
    module_url: /local/panel-redirect.js
    config:
      target: /config/server_control
  - name: panel-redirect
    url_path: redirect-logs
    sidebar_title: Logs
    sidebar_icon: mdi:math-log
    module_url: /local/panel-redirect.js
    config:
      target: /config/logs

homeassistant:
  packages: !include_dir_merge_named packages
  customize: !include customize.yaml
  time_zone: Europe/Minsk
  latitude: !secret latitude_coord
  longitude: !secret longitude_coord
#вынос во внешние файлы
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include sensor.yaml
input_select: !include input_select.yaml
timer: !include timer.yaml
alert: !include alert.yaml
media_player: !include media_player.yaml
#Настройка базы данных Maria DB
recorder: !include recorder.yaml
history: !include history.yaml

# Text to speech
tts:
#   - platform: google_translate
#     language: 'ru'
  - platform: rhvoice
    host: !secret IP_hass
    port: 8080 # Не обязательно
    format: 'mp3' # Не обязательно, wav|mp3|opus|flac
    pitch: 50 # Не обязательно, 0..100
    rate: 50 # Не обязательно, 0..100
    voice: 'anna' # Не обязательно
    volume: 50 # Не обязательно, 0..100

binary_sensor: 
  - platform: mqtt
    name: "My Computer - Connected"
    state_topic: "iotlink/workgroup/family_com/lwt"
    value_template: "{{ value }}"
    payload_on: "ON"
    payload_off: "OFF"
    device_class: "connectivity"
    qos: 1

# Обозначение комьютера и настройк его вкл/выкл
switch:
  - platform: template
    switches:
      my_computer:
        friendly_name: "My computer"
        value_template: "{{ is_state('binary_sensor.my_computer_connected', 'on') }}"
        turn_on:
          service: script.my_computer_wake
        turn_off:
          service: script.my_computer_shutdown
        icon_template: phu:desktop-computer

  - platform: template
    switches:
      all_light_child:
        friendly_name: "Весь свет в детской"
        turn_on:
          service: script.childrens_light
        turn_off:
          service: scene.turn_on
          target:
            entity_id: scene.svet_v_detskoi_vykliuchen

yeelight:
  custom_effects:
    - name: 'Мерцание огня'
      flow_params:
        count: 0
        transitions:
          - TemperatureTransition: [1900, 1000, 80]
          - TemperatureTransition: [1900, 2000, 60]
          - SleepTransition:       [1000]

telegram_bot:
  - platform: polling
    api_key: !secret token_telegram
    parse_mode: html
    allowed_chat_ids: #разрешенные пользователи
      - !secret chatid_vitaly
      - !secret chatid_inna

notify:
  - name: vitaly
    platform: telegram
    chat_id: !secret chatid_vitaly
  - name: inna
    platform: telegram
    chat_id: !secret chatid_inna

  - platform: html5
    name: vitaly_html5
    vapid_pub_key: !secret html5_PUBLIC_KEY
    vapid_prv_key: !secret html5_PRIVATE_KEY
    vapid_email: !secret email_e

# notify_events:
#   token: !secret notify_events


rest_command: # REST команды 
# Копирование snapshot в Google Drive
  google_backup:
    url: 'http://localhost:8055/gb/doBackup'
    timeout: '300'

#   turn_off: #Выключение ПК
#     url: !secret command_PC_off
#     method: get

#--------------------------------------------------------Объекты

input_boolean:
  zigbee_permit_join:
    name: Allow devices to join
    initial: off
    icon: mdi:cellphone-wireless

# Яндекс станция и языковое общение 
conversation: #возможность общаться с Яндекс станцией из интерфейса Lovelace
  intents:
    # менять нужно entity_id до двоеточия, после двоеточия ничего менять не надо!
    media_player.yandex_station_xk0000000000000130270002a0593d4f: [.+]  # замените на вашу станцию

yandex_station:
  recognition_lang: ru-RU
  tts_service_name: yandex_say
  include:
  - Телевизор

yandex_smart_home:
  notifier:
    - oauth_token: !secret yandex_token
      skill_id: !secret yandex_skill_id
      user_id: !secret yandex_user_id

#Трекинг устройств
route:
  haddr: !secret outside_hass
  days: 5
  mindst: 0.1
  time_zone: '+03:00'
  token: !secret route_token
  devices:
    - device_tracker.inna_poco
    - device_tracker.mi_note_10_pro
    - device_tracker.google_maps_kamarousky_gmail_com

device_tracker:
  - platform: google_maps
    username: !secret email_k
  - platform: google_maps
    username: !secret email_e
