
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:
homeassistant:
  packages: !include_dir_merge_named packages
  customize: !include customize.yaml
  time_zone: Europe/Minsk
  latitude: !secret latitude_coord
  longitude: !secret longitude_coord

wake_on_lan:
python_script:

frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
#   - platform: google_translate
#     language: 'ru'
  - platform: rhvoice
    host: !secret IP_hass
    port: 8080 # Не обязательно
    format: 'mp3' # Не обязательно, wav|mp3|opus|flac
    pitch: 50 # Не обязательно, 0..100
    rate: 50 # Не обязательно, 0..100
    voice: 'anna' # Не обязательно
    volume: 50 # Не обязательно, 0..100
    
lovelace:
  mode: storage

#вынос во внешние файлы
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include sensor.yaml
input_select: !include input_select.yaml
#Настройка базы данных Maria DB
recorder: !include recorder.yaml
history: !include history.yaml
media_player: !include media_player.yaml
timer: !include timer.yaml

noolite:
  port: "/dev/ttyUSB1"

binary_sensor: 
- platform: noolite
  channel: 3
  name: "Кнопка noolite вверх на кухне"
  type: remote 
- platform: noolite
  channel: 4
  name: "Кнопка noolite вниз  на кухне"
  type: remote 
- platform: noolite
  channel: 5
  name: "Кнопка в ванной"
  type: remote 

- platform: mqtt
  name: "My Computer - Connected"
  state_topic: "iotlink/workgroup/family_com/lwt"
  value_template: "{{ value }}"
  payload_on: "ON"
  payload_off: "OFF"
  device_class: "connectivity"
  qos: 1

# - platform: noolite
#   channel: 3
#   name: "battary kitchen backlight remote up"
#   type: battery 
# - platform: noolite
#   channel: 4
#   name: "battary kitchen backlight remote down"
#   type: battery 
# - platform: noolite
#   channel: 5
#   name: "battary bathroom remote"
#   type: battery
  
light:
  - platform: noolite
    channel: 0
    name: "Подсветка на кухне"
    icon: mdi:led-strip
    scan_interval: 60
    type: dimmer
    mode: noolite

  - platform: noolite
    channel: 1
    name: "Вентилятор в ванной"
    icon: mdi:fan
    scan_interval: 60
    type: dimmer
    mode: noolite
    

# Обозначение комьютера и настройк его вкл/выкл
switch:
#   - platform: wake_on_lan
#     mac: !secret MAC_PC
#     name: "Компьютер"
#     host: !secret IP_PC
#     turn_off:
#       service: rest_command.turn_off
  - platform: template
    switches:
      my_computer:
        friendly_name: "My computer"
        value_template: "{{ is_state('binary_sensor.my_computer_connected', 'on') }}"
        turn_on:
          service: script.my_computer_wake
        turn_off:
          service: script.my_computer_shutdown
        icon_template: mdi:laptop

yeelight:
  custom_effects:
    - name: 'Мерцание огня'
      flow_params:
        count: 0
        transitions:
          - TemperatureTransition: [1900, 1000, 80]
          - TemperatureTransition: [1900, 2000, 60]
          - SleepTransition:       [1000]

telegram_bot:
  - platform: polling
    api_key: !secret token_telegram
    parse_mode: html
    allowed_chat_ids: #разрешенные пользователи
      - !secret chatid_vitaly
      - !secret chatid_inna

notify:
  - name: vitaly
    platform: telegram
    chat_id: !secret chatid_vitaly
  - name: inna
    platform: telegram
    chat_id: !secret chatid_inna

rest_command: # REST команды 
#   turn_off: #Выключение ПК
#     url: !secret command_PC_off
#     method: get

# Копирование snapshot в Google Drive
  google_backup:
    url: 'http://localhost:8055/gb/doBackup'
    timeout: '300'

# notify_events:
#   token: !secret notify_events

#--------------------------------------------------------Объекты

input_boolean:
  zigbee_permit_join:
    name: Allow devices to join
    initial: off
    icon: mdi:cellphone-wireless

# создание боковой панели с иконками Material disign
# panel_iframe:
#   mdi:
#     title: "Material Design Icons"
#     icon: mdi:material-design
#     url: "https://mdi.bessarabov.com"

conversation: #возможность общаться с Яндекс станцией из интерфейса Lovelace
  intents:
    # менять нужно entity_id до двоеточия, после двоеточия ничего менять не надо!
    media_player.yandex_station_xk0000000000000130270002a0593d4f: [.+]  # замените на вашу станцию

yandex_station:
  recognition_lang: ru-RU
  tts_service_name: yandex_say

yandex_smart_home:
  notifier:
    - oauth_token: !secret yandex_token
      skill_id: !secret yandex_skill_id
      user_id: !secret yandex_user_id

alert: !include alert.yaml #повторяющаяся каждые 5 минут тревога о протечке
#   garage_door:
#     name: "Leaks"
#     done_message: "Протечка устранена"
#     entity_id: binary_sensor.0x158d0006b2542f_moisture
#     state: "on"
#     title: "Внимание, обнаружена протечка"
#     message: |
#       {% if is_state('binary_sensor.0x158d0006b233e6_moisture', 'on') %} 
#         Влажно на кухне!      
#       {% else %} 
#         На кухне сухо.
#       {% endif %}
#       {% if is_state('binary_sensor.0x158d0006b2542f_moisture', 'on') %} 
#         Влажно в ванной!      
#       {% else %} 
#         В ванной сухо.
#       {% endif %}
#       {% if is_state('binary_sensor.0x158d0006b25766_moisture', 'on') %} 
#         Влажно в туалете!      
#       {% else %} 
#         В туалете сухо.
#       {% endif %}
#     data:
#       inline_keyboard:
#         - 'Подтверждение:/Протечка_устранена'
#     repeat: 5
#     can_acknowledge: true
#     skip_first: false
#     notifiers:
#       - vitaly

route:
  haddr: !secret outside_hass
  days: 5
  mindst: 0.1
  time_zone: '+03:00'
  token: !secret route_token
  devices:
    - device_tracker.inna_poco
    - device_tracker.mi_note_10_pro
