db_url: !secret maria_db
purge_keep_days: 14 #хранение 14 дней
include:
  domains:
    - sensor
    - switch
    - shell_command
    - binary_sensor
    - input_text
    - light
    - script
    - device_tracker
  entities:
    - vacuum.valetudo_slipperyprestigiouskudu
    - sensor.hass_db_size
    - number.co2_airsensor_threshold2
    - media_player.televizor
    - climate.konditsioner
exclude:
  entities:
    - sensor.time
  #   - binary_sensor.28d1272d14e8_motion
  #   - binary_sensor.582d346033de_motion
    - sensor.domofon_uptime
    - device_tracker.14_4f_d7_41_75_48
    - device_tracker.56_e4_5e_a1_6c_19
    - device_tracker.5c_cf_7f_19_fe_54
    - device_tracker.74_51_ba_67_99_d9
    - device_tracker.lg_tv_lan
    - device_tracker.libreelec
    - device_tracker.liustra_alisy
    - device_tracker.pc
    - device_tracker.tv
    - sensor.virtual_device_tracker_inna_poco
    - sensor.virtual_device_tracker_mi_note_10_pro
    - device_tracker.d_link
    - sensor.domofon_heap_size
    - sensor.hacs
    - sensor.portable_switch_voltage
  entity_globs:
      - sensor.*_ble
      - sensor.*_zigbee
#      - sensor.transmission_*
      - sensor.*_rssi
      - sensor.*_linkquality
      - sensor.*_uptime
      - sensor.*_wifi_signal
      - camera.*
  event_types:
    - service_removed
    - service_executed
    - platform_discovered
    - homeassistant_start
    - homeassistant_stop
    - feedreader
    - service_registered
    - call_service
    - component_loaded
    - logbook_entry
    - system_log_event
    - automation_triggered
    - script_started
    - timer_out_of_sync