clean_bedroom:
  alias: "Спальня"
  sequence:
    - service: vacuum.send_command
      data:
        entity_id: vacuum.rockrobo_vacuum_v1
        command: app_zoned_clean
        params: [[24595,26661,27846,21132,1]]
clean_kids_room:
  alias: "Детская"
  sequence:
    - service: vacuum.send_command
      data:
        entity_id: vacuum.rockrobo_vacuum_v1
        command: app_zoned_clean
        params: [[24567,20861,27659,15184,1]]
clean_kitchen_hall:
  alias: "Кухня и коридор"
  sequence:
    - service: vacuum.send_command
      data:
        entity_id: vacuum.rockrobo_vacuum_v1
        command: app_zoned_clean
        params: [[21959,26296,24586,20103,1]]

clean_all_room:
  alias: "Убрать весь дом"
  sequence:
    - service: vacuum.send_command
      data:
        entity_id: vacuum.rockrobo_vacuum_v1
        command: app_zoned_clean
        params: [[24595,26661,27846,21132,1],[24567,20861,27659,15184,1],[21959,26296,24586,20103,1]]


#Кнопки для андроид ТВ
box_home:
  sequence:
    - service: androidtv.adb_command
      data:
        entity_id: media_player.android_tv # Это имя которое вы указали в настройках медиа плеера  
        command: HOME
box_power:
  sequence:
    - service: androidtv.adb_command
      data:
        entity_id: media_player.android_tv # Это имя которое вы указали в настройках медиа плеера 
        command: POWER  
box_sleep:
  sequence:
    - service: androidtv.adb_command
      data:
        entity_id: media_player.android_tv # Это имя которое вы указали в настройках медиа плеера 
        command: SLEEP        
box_up:
  sequence:
    - service: androidtv.adb_command
      data:
        entity_id: media_player.android_tv # Это имя которое вы указали в настройках медиа плеера 
        command: UP        
box_down:
  sequence:
    - service: androidtv.adb_command
      data:
        entity_id: media_player.android_tv # Это имя которое вы указали в настройках медиа плеера 
        command: DOWN        
box_left:
  sequence:
    - service: androidtv.adb_command
      data:
        entity_id: media_player.android_tv # Это имя которое вы указали в настройках медиа плеера 
        command: LEFT        
box_right:
  sequence:
    - service: androidtv.adb_command
      data:
        entity_id: media_player.android_tv # Это имя которое вы указали в настройках медиа плеера  
        command: RIGHT        
box_center:
  sequence:
    - service: androidtv.adb_command
      data:
        entity_id: media_player.android_tv # Это имя которое вы указали в настройках медиа плеера 
        command: CENTER       
box_back:
  sequence:
    - service: androidtv.adb_command
      data:
        entity_id: media_player.android_tv # Это имя которое вы указали в настройках медиа плеера  
        command: BACK        
box_menu:
  sequence:
    - service: androidtv.adb_command
      data:
        entity_id: media_player.android_tv # Это имя которое вы указали в настройках медиа плеера 
        command: MENU               
box_mute:
  sequence:
    - service: androidtv.adb_command
      data:
        entity_id: media_player.android_tv # Это имя которое вы указали в настройках медиа плеера 
        command: MUTE               
kinopoisk: 
  sequence:
  - service: androidtv.adb_command
    entity_id: media_player.android_tv # Это имя которое вы указали в настройках медиа плеера 
    data:
      command: am start -a android.intent.action.VIEW -d -n ru.kinopoisk.tv/ru.kinopoisk.tv.presentation.splash.SplashActivity