sunrise:
  alias: Sunrise Effect
  sequence:
  - service: light.turn_on
    data:
      brightness: 3
      kelvin: 1700
    target:
      entity_id: light.yeelight_ceiling1_0x3b65236_nightlight
  - delay: 00:01:00
  - service: light.turn_on
    entity_id: light.yeelight_ceiling1_0x3b65236_nightlight
    data:
      brightness: 12
      kelvin: 1800
  - delay: 00:01:00
  - service: light.turn_on
    entity_id: light.yeelight_ceiling1_0x3b65236_nightlight
    data:
      brightness: 23
      kelvin: 1800
  - delay: 00:01:00
  - service: light.turn_on
    entity_id: light.yeelight_ceiling1_0x3b65236_nightlight
    data:
      brightness: 46
      kelvin: 1900
  - delay: 00:01:00
  - service: light.turn_on
    entity_id: light.yeelight_ceiling1_0x3b65236_nightlight
    data:
      brightness: 69
      kelvin: 2000
  - delay: 00:01:00
  - service: light.turn_on
    entity_id: light.yeelight_ceiling1_0x3b65236_nightlight
    data:
      brightness: 92
      kelvin: 2100
  - delay: 00:01:00
  - service: light.turn_on
    entity_id: light.yeelight_ceiling1_0x3b65236_nightlight
    data:
      brightness: 115
      kelvin: 2200
  - delay: 00:01:00
  - service: light.turn_on
    entity_id: light.yeelight_ceiling1_0x3b65236_nightlight
    data:
      brightness: 128
      kelvin: 2300
  - delay: 00:01:00
  - service: light.turn_on
    entity_id: light.yeelight_ceiling1_0x3b65236_nightlight
    data:
      brightness: 151
      kelvin: 2400
  - delay: 00:01:00
  - service: light.turn_on
    entity_id: light.yeelight_ceiling1_0x3b65236_nightlight
    data:
      brightness: 174
      kelvin: 2500
  - delay: 00:01:00
  - service: light.turn_on
    entity_id: light.yeelight_ceiling1_0x3b65236_nightlight
    data:
      brightness: 197
      kelvin: 2600
  - delay: 00:01:00
  - service: light.turn_on
    entity_id: light.yeelight_ceiling1_0x3b65236_nightlight
    data:
      brightness: 220
      kelvin: 2700
  - delay: 00:01:00
  - service: light.turn_on
    entity_id: light.yeelight_ceiling1_0x3b65236_nightlight
    data:
      brightness: 255
      kelvin: 2700
  - service: light.turn_on
    entity_id: light.yeelight_ceiling1_0x3b65236
    data:
      brightness: 1
      kelvin: 1700
  - delay: 00:01:00
  - service: light.turn_on
    entity_id: light.yeelight_ceiling1_0x3b65236
    data:
      brightness: 23
      kelvin: 1800
  - delay: 00:01:00
  - service: light.turn_on
    entity_id: light.yeelight_ceiling1_0x3b65236
    data:
      brightness: 46
      kelvin: 1900
  - delay: 00:01:00
  - service: light.turn_on
    entity_id: light.yeelight_ceiling1_0x3b65236
    data:
      brightness: 69
      kelvin: 2000
  - delay: 00:01:00
  - service: light.turn_on
    entity_id: light.yeelight_ceiling1_0x3b65236
    data:
      brightness: 92
      kelvin: 2100
  - delay: 00:01:00
  - service: light.turn_on
    entity_id: light.yeelight_ceiling1_0x3b65236
    data:
      brightness: 115
      kelvin: 2200
  - delay: 00:01:00
  - service: light.turn_on
    entity_id: light.yeelight_ceiling1_0x3b65236
    data:
      brightness: 128
      kelvin: 2300
  - delay: 00:01:00
  - service: light.turn_on
    entity_id: light.yeelight_ceiling1_0x3b65236
    data:
      brightness: 151
      kelvin: 2400
  - delay: 00:01:00
  - service: light.turn_on
    entity_id: light.yeelight_ceiling1_0x3b65236
    data:
      brightness: 174
      kelvin: 2500
  - delay: 00:01:00
  - service: light.turn_on
    entity_id: light.yeelight_ceiling1_0x3b65236
    data:
      brightness: 197
      kelvin: 2600
  - delay: 00:01:00
  - service: light.turn_on
    entity_id: light.yeelight_ceiling1_0x3b65236
    data:
      brightness: 220
      kelvin: 2700
  - delay: 00:01:00
  - service: light.turn_on
    entity_id: light.yeelight_ceiling1_0x3b65236
    data:
      brightness: 255
      kelvin: 2700
  mode: single
  icon: mdi:weather-sunset-up
wled_random_effect:
  alias: Эффект гирлянды в детской
  sequence:
  - repeat:
      count: '300'
      sequence:
      - service: light.turn_on
        target:
          entity_id: light.wled1
        data:
          effect: '{{ state_attr(''light.wled1'', ''effect_list'') | random }}'
      - service: select.select_option
        target:
          entity_id: select.wled1_color_palette
        data:
          option: '{{ state_attr(''select.wled1_color_palette'', ''options'') | random
            }}'
      - service: number.set_value
        target:
          entity_id: number.wled1_speed
        data:
          value: '{{ (range(0, 255)|random) }}'
      - service: number.set_value
        target:
          entity_id: number.wled1_intensity
        data:
          value: '{{ (range(0, 255)|random) }}'
      - delay:
          hours: 0
          minutes: 3
          seconds: 0
          milliseconds: 0
  mode: single
  icon: phu:christmas-tree-v2
update_shopping_list:
  alias: Обновить список покупок
  sequence:
  - service: media_player.play_media
    entity_id: media_player.yandex_station_xk0000000000000130270002a0593d4f
    data:
      media_content_id: update
      media_content_type: shopping_list
  mode: single
  icon: fas:list-ol
'1638028346743':
  alias: Эффект гирлянды в спальне
  sequence:
  - repeat:
      count: '300'
      sequence:
      - service: light.turn_on
        target:
          entity_id: light.wled
        data:
          effect: '{{ state_attr(''light.wled'', ''effect_list'') | random }}'
      - service: select.select_option
        target:
          entity_id: select.wled_color_palette
        data:
          option: '{{ state_attr(''select.wled_color_palette'', ''options'') | random
            }}'
      - service: number.set_value
        target:
          entity_id: number.wled_speed
        data:
          value: '{{ (range(0, 255)|random) }}'
      - service: number.set_value
        target:
          entity_id: number.wled_intensity
        data:
          value: '{{ (range(0, 255)|random) }}'
      - delay:
          hours: 0
          minutes: 3
          seconds: 0
          milliseconds: 0
  mode: single
  icon: phu:christmas-tree-v2
yandex_volume_set:
  alias: Меняем громкость Яндекс станцииций
  sequence:
  - service: media_player.volume_set
    data:
      volume_level: 0.21
    target:
      entity_id:
      - media_player.yandex_station_xk0000000000000130270002a0593d4f
  mode: single
yandex_play_album:
  alias: Яндекс станция тест
  sequence:
  - service: media_player.play_media
    data:
      media_content_id: <speaker is_whisper="true">Хозяин, уже утро, пора вставать!
      media_content_type: dialog
    target:
      entity_id: media_player.yandex_station_xk0000000000000130270002a0593d4f
  mode: single
yandex_tts2:
  alias: Запуск колыбельной
  sequence:
  - service: media_player.play_media
    target:
      entity_id: media_player.yandex_station_xk0000000000000130270002a0593d4f
    data:
      media_content_id: сделай громче на 0
      media_content_type: command
  - delay:
      hours: 0
      minutes: 0
      seconds: 0
      milliseconds: 10
  - service: media_player.play_media
    target:
      entity_id: media_player.yandex_station_xk0000000000000130270002a0593d4f
    data:
      media_content_id: включи мой плейлист ночной на повторе
      media_content_type: command
  - delay:
      hours: 0
      minutes: 0
      seconds: 1
      milliseconds: 0
  - service: media_player.volume_set
    data:
      volume_level: 0.16
    target:
      entity_id: media_player.yandex_station_xk0000000000000130270002a0593d4f
  - choose:
    - conditions:
      - condition: state
        entity_id: switch.light_bedroom
        state: 'on'
      sequence:
      - service: switch.turn_off
        target:
          entity_id: switch.light_bedroom
    default: []
  - choose:
    - conditions:
      - condition: state
        entity_id: media_player.televizor
        state: playing
      sequence:
      - service: media_player.turn_off
        target:
          entity_id: media_player.televizor
    default: []
  - choose:
    - conditions:
      - condition: state
        entity_id: light.wled
        state: 'on'
      sequence:
      - service: light.turn_off
        target:
          entity_id: light.wled
    default: []
  - choose:
    - conditions:
      - condition: state
        entity_id: script.1638028346743
        state: 'on'
      sequence:
      - service: script.turn_off
        target:
          entity_id: script.1638028346743
    default: []
  - choose:
    - conditions:
      - condition: state
        state: 'off'
        entity_id: switch.portable_switch
      - condition: sun
        after: sunset
      sequence:
      - service: switch.turn_on
        target:
          entity_id: switch.portable_switch
    default: []
  mode: single
  icon: mdi:baby-carriage
'1638645965421':
  sequence:
  - service: media_player.play_media
    target:
      entity_id: media_player.yandex_station_xk0000000000000130270002a0593d4f
    data:
      media_content_type: command
      media_content_id: включи телевизор
  mode: single
  alias: Включить телевизор
'1638901280075':
  alias: Смена эффекта гирлянды в детской вручную
  sequence:
  - choose:
    - conditions:
      - condition: state
        entity_id: script.wled_random_effect
        state: 'on'
      sequence:
      - service: script.turn_off
        target:
          entity_id: script.wled_random_effect
    default:
    - service: light.turn_on
      target:
        entity_id: light.wled1
      data:
        effect: '{{ state_attr(''light.wled1'', ''effect_list'') | random }}'
    - service: select.select_option
      target:
        entity_id: select.wled1_color_palette
      data:
        option: '{{ state_attr(''select.wled1_color_palette'', ''options'') | random
          }}'
    - service: number.set_value
      target:
        entity_id: number.wled1_speed
      data:
        value: '{{ (range(0, 255)|random) }}'
    - service: number.set_value
      target:
        entity_id: number.wled1_intensity
      data:
        value: '{{ (range(0, 255)|random) }}'
  mode: single
  icon: phu:christmas-lights
'1639129755202':
  alias: Звонок на станцию
  sequence:
  - service: media_player.volume_set
    data:
      volume_level: 0
    entity_id: media_player.yandex_station_xk0000000000000130270002a0593d4f
  - delay: 00:00:05
  - service: media_player.play_media
    data:
      media_content_id: Сними трубку
      media_content_type: command
    entity_id: media_player.yandex_station_xk0000000000000130270002a0593d4f
  - delay: 00:00:01
  - service: media_player.volume_set
    data:
      volume_level: 0.5
    entity_id: media_player.yandex_station_xk0000000000000130270002a0593d4f
  mode: single
  icon: mdi:phone-classic
'1641317997033':
  alias: hibernate
  sequence:
  - service: mqtt.publish
    data:
      topic: iotlink/workgroup/family_com/commands/hibernate
      payload: ''
  mode: single
my_computer_wake:
  alias: My Computer - Wake
  sequence:
  - service: wake_on_lan.send_magic_packet
    data:
      mac: f4:6d:04:21:19:ef
my_computer_shutdown:
  alias: My Computer - Shutdown
  sequence:
  - service: mqtt.publish
    data:
      topic: iotlink/workgroup/family_com/commands/shutdown
      payload: ''
my_computer_suspend:
  alias: My Computer - Suspend
  sequence:
  - service: mqtt.publish
    data:
      topic: iotlink/workgroup/family_com/commands/suspend
      payload: ''
my_computer_hibernate:
  alias: My Computer - Hibernate
  sequence:
  - service: mqtt.publish
    data:
      topic: iotlink/workgroup/family_com/commands/hibernate
      payload: ''
my_computer_reboot:
  alias: My Computer - Reboot
  sequence:
  - service: mqtt.publish
    data:
      topic: iotlink/workgroup/family_com/commands/reboot
      payload: ''
my_computer_lock:
  alias: My Computer - Lock
  sequence:
  - service: mqtt.publish
    data:
      topic: iotlink/workgroup/family_com/commands/lock
      payload: ''
my_computer_logoff:
  alias: My Computer - Logoff
  sequence:
  - service: mqtt.publish
    data:
      topic: iotlink/workgroup/family_com/commands/logoff
      payload: ''
my_computer_vol_mute:
  alias: My Computer - Toggle Mute
  sequence:
  - service: mqtt.publish
    data:
      topic: iotlink/workgroup/family_com/commands/volume/mute
      payload: ''
my_computer_vol_max:
  alias: My Computer - Vol Max
  sequence:
  - service: mqtt.publish
    data:
      topic: iotlink/workgroup/family_com/commands/volume/set
      payload: '100'
my_computer_displays_on:
  alias: My Computer - Displays ON
  sequence:
  - service: mqtt.publish
    data:
      topic: iotlink/workgroup/family_com/commands/displays/on
      payload: ''
my_computer_displays_off:
  alias: My Computer - Displays OFF
  sequence:
  - service: mqtt.publish
    data:
      topic: iotlink/workgroup/family_com/commands/displays/off
      payload: ''
my_computer_refresh:
  alias: My Computer - Refresh
  sequence:
  - service: mqtt.publish
    data:
      topic: iotlink/workgroup/family_com/refresh
      payload: ''
childrens_light:
  sequence:
  - choose:
    - conditions:
      - condition: state
        entity_id: group.children_s_light
        state: 'off'
      sequence:
      - service: scene.turn_on
        target:
          entity_id: scene.svet_v_detskoi_vkliuchen
    - conditions:
      - condition: state
        entity_id: group.children_s_light
        state: 'on'
      sequence:
      - condition: state
        state: 'off'
        entity_id: switch.children_s_spotlight_l1
      - service: switch.turn_on
        target:
          entity_id: switch.children_s_spotlight_l1
      - condition: state
        entity_id: switch.children_s_spotlight_l2
        state: 'off'
      - service: switch.turn_on
        target:
          entity_id: switch.children_s_spotlight_l2
      - condition: state
        entity_id: light.yeelight_ceiling1_0x3b65236
        state: 'off'
      - service: light.turn_on
        target:
          entity_id: light.yeelight_ceiling1_0x3b65236
        data:
          brightness_pct: 100
    default: []
  mode: single
  alias: Включить весь свет в детской
  icon: mdi:lightbulb-group
kodi:
  sequence:
  - service: wake_on_lan.send_magic_packet
    data:
      mac: b8:27:eb:66:a8:72
  mode: single
  alias: Коди включить
  icon: mdi:kodi
kodi_2:
  alias: Коди выключить
  sequence:
  - service: kodi.call_method
    target:
      entity_id: media_player.libreelec
    data:
      method: System.Shutdown
  mode: single
  icon: hue:lightstrip-tv-off
kodi_3:
  alias: Коди обновить библиотеку
  sequence:
  - service: kodi.call_method
    target:
      entity_id: media_player.libreelec
    data:
      method: VideoLibrary.Scan
  mode: single
  icon: mdi:database-sync-outline
kodi_4:
  alias: Коди очистить библиотеку
  sequence:
  - service: kodi.call_method
    target:
      entity_id: media_player.libreelec
    data:
      method: VideoLibrary.Clean
  mode: single
  icon: mdi:database-minus-outline
'1644400678872':
  alias: 'Включение входа Яндекс '
  sequence:
  - service: media_player.select_source
    data:
      entity_id: media_player.televizor
      source: HDMI3
  mode: single
'1644400833935':
  alias: Включение входа Коди
  sequence:
  - service: media_player.select_source
    target:
      entity_id: media_player.televizor
    data:
      source: HDMI2
  mode: single
'1644486924270':
  alias: Переключить на коди
  sequence:
  - service: media_player.play_media
    target:
      entity_id: media_player.yandex_station_xk0000000000000130270002a0593d4f
    data:
      media_content_id: сделай громче на 0
      media_content_type: command
  - choose:
    - conditions:
      - condition: state
        entity_id: media_player.televizor
        state: playing
      - condition: template
        value_template: '{% if is_state_attr("media_player.televizor", "source", "HDMI3")%}
          True {% else %} False {% endif %}'
      sequence:
      - service: media_player.play_media
        data:
          media_content_type: command
          media_content_id: включи источник 2
        target:
          entity_id: media_player.yandex_station_xk0000000000000130270002a0593d4f
    - conditions:
      - condition: state
        entity_id: media_player.televizor
        state: 'off'
      sequence:
      - service: script.1638645965421
        data: {}
      - delay:
          hours: 0
          minutes: 0
          seconds: 30
          milliseconds: 0
    default: []
  - choose:
    - conditions:
      - condition: template
        value_template: '{% if is_state_attr("media_player.televizor", "source", "HDMI3")%}
          True {% else %} False {% endif %}'
      sequence:
      - service: media_player.play_media
        data:
          media_content_type: command
          media_content_id: включи источник 2
        target:
          entity_id: media_player.yandex_station_xk0000000000000130270002a0593d4f
    default: []
  mode: single
  icon: mdi:kodi
