# Use this file to store secrets like usernames and passwords.
# Learn more at https: ""
some_password: ""
maria_db: ""
token_vacuum: ""
latitude_coord: ""
longitude_coord: ""
token_telegram: ""
# токен для transmission бота: ""
chatid_vitaly: ""
chatid_inna: ""
token_lg: ""
notify_events: ""
xiaomi_vacuum_host: ""
xiaomi_cloud_username: ""
xiaomi_cloud_password: ""
#narodmon_api: ""
aimp_ip: ""
narodmon_api: ""
IP_hass: ""
outside_hass: ""
MAC_PC: ""
IP_PC: ""
MAC_TV: ""
IP_TV: ""
IP_TVBOX_A1: ""
command_PC_off: ""
IP_vacuum: ""
admin_pass: ""
hass_pass: ""
hass_login: ""
database_maria: ""
yandex_token: ""
yandex_skill_id: ""
yandex_user_id: ""
route_token: ""