'0x5c0272fffeedfbe1':
  friendly_name: light switch coridor
'0xcc86ecfffefa94ae':
  friendly_name: Portable switch
'0x00124b0022ffca0d':
  friendly_name: CO2 sensor
'0xb4e3f9fffe22a8b6':
  friendly_name: PC switch
'0x0c4314fffe62ca51':
  friendly_name: light-bedroom
'0xb4e3f9fffe22b03b':
  friendly_name: kidd's spotlights
